### ISSUE TITLE
Add NeoForge - Advanced 

### ISSUE THREAD

**Issue by SNokerYT** [wisp-gg/issue-tracker#57] opened 2024-09-10 02:05 UTC
### Describe the feature and why you would like to see it.

Version - NeoForge 

### Describe the solution you'd like.

Version - NeoForge

**Comment by pedrotski** [comment] 2024-09-10 07:21
Issue already exists - https://github.com/wisp-gg/issue-tracker/issues/43

**Comment by anthonyphysgun** [comment] 2024-09-10 19:34
Duplicate of https://github.com/wisp-gg/issue-tracker/issues/43

**Closed by anthonyphysgun** 2024-09-10 19:34 UTC
