### ISSUE TITLE
Disk Space

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/issue-tracker#44] opened 2024-08-29 16:19 UTC
### Describe the bug

People can upload and use more space than the limit the space is only checked when the server is going to start, so if the server is already running can pass the disk space also if it’s stopped.

### Expected Behavior

Unable to exceed disk limit

### Actual Behavior

Able to exceed disk limit

### Steps to Reproduce

Just add more files or put pot some code to exceed the limit (generate trash space).

### Browser Details

Chrome

### Operating System

Windows

**Comment by Lunaversitay** [comment] 2024-09-10 00:37
duplicate of #33

**Closed by Lunaversitay** 2024-09-10 00:37 UTC
Labels: Dupe
